### ISSUE TITLE
Package DBMS_LOCK not included

### ISSUE THREAD

**Issue by geirsagberg** [gvenzl/oci-oracle-free#11]
Hello! I am attempting to use https://github.com/blagerweij/liquibase-sessionlock to avoid hanging locks with Liquibase. This package depends on [DBMS_LOCK](https://docs.oracle.com/en/database/oracle/oracle-database/19/arpls/DBMS_LOCK.html#GUID-ABF571D1-443D-4528-BDD2-50768B4D1898) being present, but it does not seem to be included:

```
SELECT *
FROM ALL_OBJECTS
WHERE OBJECT_TYPE = 'PACKAGE'
  AND OBJECT_NAME = 'DBMS_LOCK';
```

Returns 0 results. This is both in the full and regular image.

Would it be possible to include this package?

**Comment by loiclefevre** [comment]
Hi @geirsagberg, which image are you using? which account did you use to run that query?

**Comment by geirsagberg** [comment]
My bad, I forgot to set `ALTER SESSION SET CONTAINER = FREEPDB1`.
