### ISSUE TITLE
Access to root in order to install commands like (ps, vim, ...)

### ISSUE THREAD

**Issue by gduvalsc** [gvenzl/oci-oracle-free#12]
Hello Gerald,

Congratulations for your work! Could you give a way to access to "root" in order to install other commands with apk.

Thanks.

Gerard

**Comment by gvenzl** [comment]
Hi @gduvalsc,

Thanks a lot for using these images!

You can SSH into the container via the `-u=0` option, i.e. `podman exec <container name|id> -u=0 bash` and then install any software via `microdnf`.

If you need software persistent in an image, you can simply expand the image, switch to the root user via `USER root` and install the software with `microdnf`.

Hope this helps!

**Comment by gduvalsc** [comment]
Hi Gerald

Thanks a lot!

Gérard

**Comment by gvenzl** [comment]
You are welcome!
