### ISSUE TITLE
SQL client to use for testing?

### ISSUE THREAD

**Issue by snow6oy** [gvenzl/oci-oracle-free#15]
hi, thanks for providing this image. Everything ran ok on my Apple M1 Mac, until this point.

`[gvenzl@localhost init_scripts]$  sql test/test@//localhost/FREEPDB1`

As a Postgres user I would write `psql` instead of `sql` to start the client and connect to the db. Did you mean to write `sqlplus` here?

**Comment by gvenzl** [comment]
Hi @snow6oy,

Thanks a lot for using these images!

I apologize, I was connecting into the container via my locally installed [SQLcl](https://www.oracle.com/sqlcl), which does come as just a `sql` binary. However, you are right, SQLcl is not installed inside the container, so the best solution would be to show `sqlplus` here, which is also available inside the container.

I will fix the ReadMe. Thank you very much for bringing this to my attention.

But for what it's worth, I recommend installing SQLcl locally. I have a [simple script over here](https://github.com/gvenzl/oracle-tools/tree/main/sqlcl) that I use on my Mac.

**Comment by snow6oy** [comment]
Happy to help. And thanks for the additional info, heading over to have a look at SQLcl now..
