### ISSUE TITLE
what an awesome project

### ISSUE THREAD

**Issue by avandenberghe** [gvenzl/oci-oracle-free#19]
hi there, 

just a note to say Thank you. 

best regards
Andreas

**Comment by gvenzl** [comment]
Wow, thanks a lot, @avandenberghe!
It's very nice to hear that the work here is appreciated!

However, the thanks really should go to you and all the other users out there.
Without you, this repository wouldn't be much more than a code dump from a weekend project! :)

Please let me know if you have any projects that you would want me to highlight at https://github.com/gvenzl/oci-oracle-free/blob/main/README.md#users-of-these-images
