### ISSUE TITLE
Add rsim/oracle-enhanced to users of oci-oracle-free

### ISSUE THREAD

**Issue by yahonda** [gvenzl/oci-oracle-free#24]
Thank you for providing Oracle Database 23c Free as a docker image.
Please add rsim/oracle-enhanced repository to https://github.com/gvenzl/oci-oracle-free#users-of-these-images .

rsim/oracle-enhanced migrated from `oci-oracle-xe` to `oci-oracle-free` via https://github.com/rsim/oracle-enhanced/pull/2352

Refer to the old request. https://github.com/gvenzl/oci-oracle-xe/issues/66 . I have not updated the docker image for rsim/ruby-plsql yet. will update when it is completed.

**Comment by gvenzl** [comment]
Thanks a lot, @yahonda, and as usual, thanks for using these images!

Do you think that https://github.com/rsim/ruby-plsql will follow anytime soon?

**Comment by yahonda** [comment]
I've started working on that and found some failing tests https://github.com/rsim/ruby-plsql/pull/231 . so it would take some more time for `rsim/ruby-plsql` to run `oci-oracle-free`

**Comment by gvenzl** [comment]
Ah I see, thank you!
