### ISSUE TITLE
Update comments about DB on ARM

### ISSUE THREAD

**Issue by cjbj** [gvenzl/oci-oracle-free#25]
The top level readme is out of date regarding availability of Oracle DB on ARM - this is now available from container-registry.oracle.com/database/enterprise:19.19.0.0

**Comment by gvenzl** [comment]
Thanks, Chris, but unfortunately Oracle Database Free is still not available on ARM, and as this repository only concerns itself with Oracle Database Free, pointing users to a different edition (with a different license requirement) would be misleading.

I do spot that I omitted one "Free" in:

> [Oracle Database Free on Apple M chips](https://github.com/gvenzl/oci-oracle-free#oracle-database-free-on-apple-m-chips)
Currently, there is no Oracle Database port for ARM chips, hence Oracle Database Free images cannot run on the new Apple M chips via Docker Desktop. 

I will correct that.

**Comment by cjbj** [comment]
Good point about free, but it would still be worth pointing people at the ARM image since it may fit their purposes better.

**Comment by gvenzl** [comment]
Added clarification for the Oracle Database Free missing port for ARM.
