### ISSUE TITLE
How to create three or n databases, you can pass an array in the string variable of ORACLE_DATABASE

### ISSUE THREAD

**Issue by habolanos** [gvenzl/oci-oracle-free#26]
Is it possible to create three or n databases, can an array be passed in the ORACLE_DATABASE string variable?

How could you create more databases in a single Docker container?

My idea is set ORACLE_DATABASE=ORCL1, ORCL2, ORCL3....ORCLn and upgrade routine to know how read this array when make db

**Comment by gvenzl** [comment]
Hey @habolanos,

Thanks a lot for using these images!

This is a very interesting idea! Currently `$ORACLE_DATABASE` cannot contain more than one database name but it wouldn't be very hard to accept a list of database names separated by a comma.

The only other way to currently do it would be to use a custom setup script and create them manually.

**Comment by gvenzl** [comment]
This is now implemented.

Thanks again for the great suggestion, @habolanos!

**Comment by habolanos** [comment]
Hi Gerald, thanks so much for your working on this req
I am a professor university on Cali, Colombia and I always use this image in my class, your image is a lot popular in the university.

Again, thanks so much!

**Comment by gvenzl** [comment]
Oh wow, thanks a lot for telling me, @habolanos!

I feel very honored that my images make it all the way into university classrooms!

I'd be happy to record a little thank you video for your students, if you like and think that they would appreciate it.

Also, just in case you are looking for some sample data to work with, feel free to check out my https://github.com/gvenzl/sample-data repository.
The data in there is all under CC BY 4.0 and the country and solar system data sets contain real information.

Thanks,

**Comment by habolanos** [comment]
Hi Gerald.

Today I recorded a video clip with my students, please check it here https://campusuccedu-my.sharepoint.com/:v:/g/personal/harold_bolanosrod_campusucc_edu_co/EZOjU8WpLixHma9tGmGxFNABtSwbMu8W00QCr3DLazbqHQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=aGjUDo

**Comment by gvenzl** [comment]
Hey @habolanos,

I watched the video a long time ago but somehow I've failed to answer and thank you here!

Thanks for the nice video, and again for using these images in your classroom!
Please also pass on my gratitude to all your students!
