### ISSUE TITLE
SQL Developer connection

### ISSUE THREAD

**Issue by NguyenVietPhuQuy** [gvenzl/oci-oracle-free#31]
Hi Mr.gvenzl. I have install oracle 23c with your container already. However, it seems that I can't connect to SQL Developer with the error "Got minus one from a read call,connect lapse 2ms., ...". I research that it's about DISABLE_OOB=ON but docker sqlora.net file on container set it on already. So, could you please help me for this issue? I don't know how to config it right.

**Comment by gvenzl** [comment]
Hi @NguyenVietPhuQuy,

Thanks a lot for using these images!

Could you please provide some more information as to how you are trying to access the container?

Can you post the `docker run` command that you are using as well as a screenshot from your SQL Developer Connection Wizard window?

Thanks,

**Comment by NguyenVietPhuQuy** [comment]
Sorry for being late response and much Thanks for your support.Here is my docker run command
docker run  --name oracledba -d -p 1904:1903 -e ORACLE_PASSWORD=<your password> -v oracle-volume:/opt/oracle/oradata gvenzl/oracle-free
I'm using Oracle Client by tnsname.ora with this script:
ORACLE23C =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1904))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = service_names)
    )
  )
Then I try to connect to PL/SQL Developer but It's shown message 'Tns connection close'
Thanks.

**Comment by gvenzl** [comment]
Hi @NguyenVietPhuQuy,

The container doesn't expose the listener on port `1903` but instead on port `1521`, so your port forwarding command line option should be `-p 1904:1521`.

Also, `SERVICE_NAME` in the tnsnames.ora will have to point to either `FREE` or `FREEPDB1`.

Hope this helps!
