### ISSUE TITLE
SQL Developer Connection

### ISSUE THREAD

**Issue by MJCandil** [gvenzl/oci-oracle-free#32]
Hello,

Thank you for your great tutorial posted https://itnext.io/oracle-on-arm-mac-m1-m2-docker-images-99ed67ed6ba6.

I was able to create the image and the test using the Mac terminal worked without issues. I'm now trying to connect SQL Developer installed in my Mac with Oracle but I'm getting the error "Invalid username/password". I've read all the documentation in the Read.me file and have tried lots of combinations but I keep getting this error. Here's my input:

Role: SYSDBA
Hostname: 127.0.0.1
Port: 1521
Service name: FREEPDB1

What's the Username and Password? I have not made any changes to the original installation, I followed your instructions to the dot. 

I am able to create the connection using the default Role, but I need to be SYSDBA.

Thank you for your help!

**Comment by gvenzl** [comment]
Hi @MJCandil,

Thanks a lot for your kind words but I'm afraid there must be a mistake.

It wasn't me who wrote the tutorial on itnext.io, nor are the images shown in the post from this repository but a derivative.

Thanks,

**Comment by Fleury93** [comment]
Hi @gvenzl, 
I appreciate your effort, you do amazing work. 
Maybe you can include the ARM build of Oracle 19 in your repositories. It seems to me only download ARM Oracle and use your script to build images enough.


@MJCandil 
I am using build for ARM on my Apple silicon too. SYSDBA works for me. 

Docker run: `docker run -p 1521:1521 -e ORACLE_PASSWORD="system" oracle/database:19.3.0-ee-slim-faststart .`
Oracle connection string: `jdbc:oracle:thin:@//localhost:1521/FREEPDB1`
Oracle user: `sys as sysdba`
Oracle password: `system`

Try it, should work.

**Comment by MJCandil** [comment]
@gvenzl,
Well, thank you for providing the origins!

@Fleury93 ,
It did work, thank you so much, really appreciate your help!
