### ISSUE TITLE
JDK Directory not available in container

### ISSUE THREAD

**Issue by Prak141** [gvenzl/oci-oracle-free#38]
I am trying to run the "loadjava" to load some of the java objects but it failed with Java not found error on researching further found that oracle_jvm is not installed, is there direct option in this container to enable or install oracle_jvm

**Comment by gvenzl** [comment]
Hi @Prak141,

Thank you very much for using these images!

You will have to use the `23-full` image, as OJVM has been removed in [the regular image](https://github.com/gvenzl/oci-oracle-free/blob/main/ImageDetails.md#regular-image-flavor-23).
