### ISSUE TITLE
Latest image no longer booting

### ISSUE THREAD

**Issue by Sanne** [gvenzl/oci-oracle-free#4]
CI jobs in Quarkus started failing.
The log finishes with:

```
CONTAINER: DONE: Creating pluggable database, duration: 7 seconds.
CONTAINER: application database not ready for service, aborting!
Please report a bug at https://github.com/gvenzl/oci-oracle-free/issues with your environment details.
```

Locally I have the same problem; I start the image with the following command:

```
podman run --rm --name HibernateTestingOracle -e ORACLE_PASSWORD=hreact -e APP_USER=hreact -e APP_USER_PASSWORD=hreact -e ORACLE_DATABASE=hreact -p 1521:1521 docker.io/gvenzl/oracle-free:23.2-slim-faststart
```
I'm running Fedora Linux v38 with
 -  kernel `6.2.13-300.fc38.x86_64`
 - podman 4.5.0

The Quarkus CI is using a regular docker on Ubuntu, so I don't think the podman version or kernel versions are relevant.

I hope you could fix it quickly as while I can switch images to prevent the Quarkus CI from failing further, the already released Quarkus versions are also referring to this image so our users are going to have a bad experience when working with the Oracle DB when using "dev services" (the capability for which we automatically start an Oracle container for users for development environments).

**Comment by Sanne** [comment]
I tested also `docker.io/gvenzl/oracle-free:23.2-slim`, same problem.

**Comment by michalvavrik** [comment]
+1 I also hit this one https://github.com/quarkus-qe/quarkus-test-framework/pull/769

**Comment by michalvavrik** [comment]
@Sanne I didn't find a Quarkus issue, am I not looking correctly?

**Comment by gvenzl** [comment]
Thanks for reporting this issue! Will look at it immediately. I think it's to do with the lowercase database name. As a potential quick verification and workaround, is it possible to quickly try with `-e ORACLE_DATABASE=HREACT`?

**Comment by gvenzl** [comment]
Confirmed, the issue is a bug with the lowercase database name, hotfix is on the way, standby.

**Comment by gvenzl** [comment]
Hey @Sanne, @michalvavrik,

The hotfix has been applied and new images uploaded.
I triple-verified (all image variants) and the database is booting up again.

Could you please verify at your end and reopen the issue if you still are encountering this?

Thanks,

**Comment by michalvavrik** [comment]
I can confirm the issue is fixed.

**Comment by gvenzl** [comment]
Ah great, thanks a lot @michalvavrik!
