### ISSUE TITLE
Changing the SID causes a error on startup

### ISSUE THREAD

**Issue by drmaniac** [gvenzl/oci-oracle-free#40]
Add new ORACLE_SID environment to the Dockerfile

```
ENV ORACLE_SID=NEWSID
```

If I start this container
```
Attaching to db-1
db-1  | CONTAINER: starting up...
db-1  | CONTAINER: first database startup, initializing...
db-1  | mv: cannot stat '/opt/oracle/product/23c/dbhomeFree/dbs/spfileNEWSID.ora': No such file or directory
```

**Comment by gvenzl** [comment]
Hi @drmaniac,

Thanks a lot for your interest in these images.

The `ORACLE_SID` is not configurable for Oracle Database Free and hence also not for these images.

**Comment by drmaniac** [comment]
Hi @gvenzl ,
Thanks for the clarification
