### ISSUE TITLE
Power Architecture support for oracle-free:23-slim-faststart image 

### ISSUE THREAD

**Issue by shreyakajbaje** [gvenzl/oci-oracle-free#42]
Hi @gvenzl working on getting this oracle-free:23-slim-faststart image ported on PPC64LE(Power) architecture. Could you please share the steps and dockerfile to get the image created? Thanks in advance.

**Comment by gvenzl** [comment]
Hi @shreyakajbaje,

The steps and Dockerfile are in this repository.

Good luck!
