### ISSUE TITLE
Release 19c request

### ISSUE THREAD

**Issue by zachy** [gvenzl/oci-oracle-free#43]
Hi,
I admire your work and I use your images in many projects. Could you create a docker image for Oracle 19c (Version 19.21.0.0.0)?

Thanks for all your work!

**Comment by gvenzl** [comment]
Thank you very much, @zachy!

Unfortunately, there is no version of Oracle Database Free for 19c and the version in question (19.21) is only available for Oracle Database Enterprise Edition and Standard Edition 2.

Neither of these editions, Oracle Database Enterprise Edition and Oracle Database Standard Edition 2, are available under Oracle's Free Use Terms and Conditions (FUTC) and hence I cannot build images of these editions nor would I be allowed to redistribute them.
Additionally, the `.21` is a Release Update (RU), which is only available to customers with an active support contract.

However, the good news is that Oracle provides images of that version over at their Container Registry (container-registry.oracle.com) where you can also find the particular version in question: https://container-registry.oracle.com/ords/ocr/ba/database/enterprise_ru

Thanks,
