### ISSUE TITLE
Unexpected empty result with Oracle Database v23/Free when NLS_COMP = 'LINGUISTIC' and bind params are used

### ISSUE THREAD

**Issue by mvorisek** [gvenzl/oci-oracle-free#44]
The current images on Docker Hub are 4 months old.

I wonder what are the sources of the build - can a new build be made and tagged?

I am having an issue with https://forums.oracle.com/ords/apexds/post/unexpected-empty-result-with-oracle-database-v23-free-when-8049 - according to the forum the bug is tracked under 35669467 in Oracle bugtracker. If I understood the last post there correctly, it should be already fixed in v23c, is that true?

**Comment by gvenzl** [comment]
Hi @mvorisek,

There hasn't been a newer release of Oracle Database Free yet.
Once there is, you can be assured that I will provide updated images with the new version of Oracle Database Free.

As for the bug, I'll check next week whether it is indeed fixed or not.

**Comment by gvenzl** [comment]
Hey @mvorisek,

I did double-check and the fix is coming with 23.4.
Once that version is released, I will provide that as a Docker image as well.

Thanks,

**Comment by mvorisek** [comment]
I belive this is fixed now, thank you all!
