### ISSUE TITLE
Provide a way to pass list of parameters to change in an environment variable

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-free#52]
This would be helpful to have an environment variable that could be used to configure database parameters (of course a restart would then occur):
- `ORACLE_DB_PARAMETERS=max_string_size:EXTENDED;vector_memory_size=1G`

Even the listener could be considered:
- `ORACLE_LISTENER_PARAMETERS=DISABLE_OOB=off`

**Comment by gvenzl** [comment]
Thanks @loiclefevre,

I'm quite hesitant to implement such a requirement as there are numerous parameters that, when set to an invalid value, will prevent the database from starting up and subsequently kill the container immediately.

A better approach might be to provide a set of setup scripts that can be mounted into the `/container-entrypoint-initdb.d` facility. Such scripts would also automatically take care of the order of the steps executed, or parameters set.

**Comment by loiclefevre** [comment]
Thanks, will do that!
