### ISSUE TITLE
Openshift deployment issues

### ISSUE THREAD

**Issue by paulushcgcj** [gvenzl/oci-oracle-free#59]
Hi there.

I have a project that is deployed on openshift and it connects to an external data center with a full Oracle Database cluster running. Recently, as part of our process of automating some of the test scenarios, we've been working on deploying an instance of this database on openshift for automated test purposes, where we would point our app to this instance and run our tests and then check the resulting data inside the database.

The problem is that the deployment of the database is inconsistent. Over the past 4 weeks, I've been trying to deploy an instance with some variations of errors, ranging from permission due to the non-root user that openshift uses to some other errors that put the database in a constant loop. 

Last week I managed to spin the database, but this week, as I was working in some other tasks, the database entered a loop and failed 100% of the time.

The most recent loop error is this one, but the first time it initializes it show a different error for a fraction of a second and restart but I'm unable to capture it.

```sh

CONTAINER: starting up...
CONTAINER: database already initialized.
CONTAINER: starting up Oracle Database...
LSNRCTL for Linux: Version 23.0.0.0.0 - Production on 27-AUG-2024 17:37:23
Copyright (c) 1991, 2023, Oracle. All rights reserved.
Starting /opt/oracle/product/23c/dbhomeFree/bin/tnslsnr: please wait...
TNSLSNR for Linux: Version 23.0.0.0.0 - Production
System parameter file is /opt/oracle/product/23c/dbhomeFree/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/nr-forest-client-tools-legacydb-14-6vdhb/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_FREE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_FREE)))
STATUS of the LISTENER
------------------------
Alias LISTENER
Version TNSLSNR for Linux: Version 23.0.0.0.0 - Production
Start Date 27-AUG-2024 17:37:24
Uptime 0 days 0 hr. 0 min. 0 sec
Trace Level off
Security ON: Local OS Authentication
SNMP OFF
Default Service FREE
Listener Parameter File /opt/oracle/product/23c/dbhomeFree/network/admin/listener.ora
Listener Log File /opt/oracle/diag/tnslsnr/nr-forest-client-tools-legacydb-14-6vdhb/listener/alert/log.xml
Listening Endpoints Summary...
(DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_FREE)))
(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ORA-01081: cannot start already-running ORACLE - shut it down first
```

Any idea on what kind of changes are required for it to run on openshift? I'm not planning on using it as a production database, I just need it as an ephemeral database, to run automated tests and discard after.

**Comment by gvenzl** [comment]
Hi @paulushcgcj,

First of all, thanks for using these images!

Unfortunately, I have no experience with OpenShift but I assume it behaves like other Kubernetes clusters.

The most recent error you get means that the instance is already running, as the error message suggests.
The curious part here is that this should technically not be possible when this is a new container.

> The most recent loop error is this one, but the first time it initializes it show a different error for a fraction of a second and restart but I'm unable to capture it.

Is the restart a new container that OpenShift creates or does it try to restart the container? If it is the same container, the previous error should be available in the container log. Yet, the above output suggests that this is a new container.

Are you using volumes at all, or is this all transient?

**Comment by paulushcgcj** [comment]
Closing this issue as I found the problem. I'll list here a few things I had to do to make it work; maybe, this can turn into something easier to handle in the future. I'll drop a link to [our repository here](https://github.com/bcgov/nr-forest-client) for reference on how we're using this image to automate some of our test cases. We created a new [Dockerfile](https://github.com/bcgov/nr-forest-client/blob/main/legacydb/Dockerfile) to accommodate some of the specific scripts and configurations we had to create and set, along with the Openshift workflow we used to [deploy and create per-pr databases](https://github.com/bcgov/nr-forest-client/blob/main/.github/workflows/pr-open.yml#L116) and also when [cleaning up after the PR is done](https://github.com/bcgov/nr-forest-client/blob/main/.github/workflows/pr-close.yml#L23).

In the end, we achieved what we were looking for, an ephemeral oracle database that we could use to run automated tests without the restrictions that we had when using the existing test environment. I hope this can be used as an example for others to leverage this image on their workflows as well.

##  Don't run as root

That's obvious, and it is something I wasn't doing, but I tried it once. **Cloud providers would usually run your container with a lower-level user/user-id.**

## Allow user id being set externally

Openshift sets one user-id that is not the same as the id used by the image itself. Compared with other databases, such as Postgres (that I use in the same project, to be honest) the user-id being passed by the platform was being used without any hiccups by Postgres. On the other end, I had to create a new **Dockerfile** to set the same ID for the user (as I noticed that Openshift will set the same user-id for the same deployment on the same namespace). **The takeaway here is that the container should be able to accept the user-id provided by the platform more easily.**

## 2gigs is the minimal

In our case, we usually go with one set of applications/services per pull request, which means I can have any number of deployments inside the same namespace. This means I had to be more creative as to how to deploy it, and we ended up with a single instance using multiple services. But, due to that, we had to increase the amount of memory as well from 2 up to 4GB. So, **when deploying to a cloud provider, make sure you can afford that.**

## File permission

Some files require specific user permissions for the database to run. When I was testing using a PVC (Persistent Volume Claim), I noticed that when I had to deploy a new instance of the database, the database itself tended to freak out because the files already existed with permissions to the user who created the files in an older deployment. Due to that, I struggled a little to deploy it using a PVC, and in the end, as it was being used for an ephemeral test environment anyway, I decided to drop the PVC and use ephemeral storage that will be gone in case of another instance being deployed. To accommodate that, we deployed in a different namespace that we can then keep an instance always up and running for our test cases, but one of our options initially was to have this specific instance coming down if we have no pull request open and the instance being deployed in case no instance is found. **The takeaway here is to be mindful when dealing with storage for the database in cloud environments where you can have an unexpected user-id being used to generate the files.**

## Database management scripts

One thing that was a lifesaver was the already-provided scripts to create databases and users. We used that as part of our automation to generate user and database per pull request.  The only problem was to roll back what was done once the pull request was complete, and for that, we had to create our script that handles the eviction of the database, user and service when we don't need it anymore. In comparison with the older [oracle db version(https://github.com/gvenzl/oci-oracle-xe) it was a big improvement with the separate scripts for database and user creation, but it is still missing an easy-to-reuse script to drop things. As this image (at least for me and my team) is not something we would roll out to production anyway (due to licensing and all things related to Oracle), having a script that can destroy the entire database is not something we would worry about. **It was easy to implement a new script based on the ones provided**
