### ISSUE TITLE
ORACLE_HOME and sqlplus

### ISSUE THREAD

**Issue by beperev** [gvenzl/oci-oracle-free#60]
Hi!
I want to create a database from a sh script in a github repository which already includes gvenzl/oracle-free. Could you tell me where is the ORACLE_HOME path and sqlplus to execute the database creation instructions?
Thank you!

**Comment by gvenzl** [comment]
Hey @beperev,

Thanks a lot for using these images!

The `ORACLE_HOME` is `/opt/oracle/product/23ai/dbhomeFree`, sqlplus is in `$ORACLE_HOME/bin`

The `ORACLE_HOME` environment variable is already set and so is `PATH` to include `$ORACLE_HOME/bin`.
So you should be able to just invoke `sqlplus` in your shell script.

**Comment by beperev** [comment]
Thank you very much.

Just another question, is there any possibility of accessing by using JDBC connection with SID (jdbc:oracle:thin:@localhost:1521:SID), instead of by using Service Name (jdbc:oracle:thin:@localhost:1521/SN)? I have tried with free as SID  but with no success.

Thank you very much.
