### ISSUE TITLE
another arm64 support question

### ISSUE THREAD

**Issue by fargue** [gvenzl/oci-oracle-free#63]
with latest [Oracle/docker-images changes](https://github.com/oracle/docker-images/pull/2868), it looks like an arm64 version is now available. I'm able to use the images built from that repo, but I'm hoping you'll incorporate them here. Any plans to do so?

**Comment by gvenzl** [comment]
Hey @fargue,

They already are up on the registries and I'm in the middle of updating this repository as well :)

Thanks for using these images!

**Comment by fargue** [comment]
Great news. Thanks a ton for these images!

**Comment by hfhbd** [comment]
Thank you! 🚀
