### ISSUE TITLE
Is perl available on oracle-free:latest?

### ISSUE THREAD

**Issue by hp-dv** [gvenzl/oci-oracle-free#66]
Hello,
I'm trying to set MAX_STRING_SIZE to EXTENDED. To complete the catcon.pl script needs to be run.
But I don't seem to be able to find perl on the oracle-free:latest?

Much obliged!

**Comment by gvenzl** [comment]
Hi @hp-dv,

Thanks a lot for using these images!

Yes, perl is available in `oracle-free:latest` and can be found under $ORACLE_HOME/perl:

```
[gvenzl@localhost ~]$ podman run --name test --rm -ti --entrypoint=bash gvenzl/oracle-free:latest
bash-4.4$ cd $ORACLE_HOME/perl
bash-4.4$ ./bin/perl -v

This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-thread-multi

Copyright 1987-2023, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.

bash-4.4$
```

**Comment by hp-dv** [comment]
Hi Gerald,

I managed to go back and stare at $ORACLE_HOME at least three times and still completely overlook the perl directory.
Thank you for your help and for making these images available!

Have a good one,
Herbert

**Comment by gvenzl** [comment]
Hehe, it happens sometimes! :)

Glad to hear that it worked out!
