### ISSUE TITLE
Wait for finishing scripts in container-entrypoint-initdb.d

### ISSUE THREAD

**Issue by tkleiber** [gvenzl/oci-oracle-free#69]
Hi!

I have to wait for the execution of the scripts in container-entrypoint-initdb.d. There I install for example:

- utPLSQL core
- utPLSQL cli
- JAVA for utPLSQL cli

I want to start a fresh container followed be liquibase migration and automated test, followed by shutdown of the container.

The problem is, that I cannot start my tests before all of the scripts are successful.
So I need something like a second healthcheck, as I don't know when and if the scripts run succesful.

The original healthckeck is required to wait before the scripts in container-entrypoint-initdb.d can start.

Do you have an idea how to solve this problem?

Best regards
Torsten

**Comment by gvenzl** [comment]
Hi @tkleiber,

Thanks for using these images!

The easiest way would be to look in the container log for `"DATABASE IS READY TO USE"`:

https://github.com/gvenzl/oci-oracle-free/blob/8acd06867c6d53359d594f62f3f23a736eae03af/container-entrypoint.sh#L447

Which is printed (right) after the user scripts have been executed:

https://github.com/gvenzl/oci-oracle-free/blob/8acd06867c6d53359d594f62f3f23a736eae03af/container-entrypoint.sh#L425-L428

https://github.com/gvenzl/oci-oracle-free/blob/8acd06867c6d53359d594f62f3f23a736eae03af/container-entrypoint.sh#L440-L448

So, something like this, for example:

```bash
while :
do
  if docker logs <container> | grep -qF 'DATABASE IS READY TO USE!'; then
    do-stuff...
    break;
  fi;
done;
```

The more reliable way would be for the last setup script (they are run in alphabetical order) to set an environment variable or create an empty file, etc. to indicate that the setup has finished for which the test scripts look out for.

Hope this helps!

Thanks,

**Comment by tkleiber** [comment]
Have now used the second solution.
As I already create in the last script a env file with the JAVA_HOME variable I check in a loop for the existence of the string in the File immediatly after starting the Database via docker compose.

Thanks!
