### ISSUE TITLE
Add OCI development files such as  `oci.h` to the container?

### ISSUE THREAD

**Issue by vadz** [gvenzl/oci-oracle-free#72]
It would be great if this container could include the headers needed for compiling C programs using OCI, i.e. `oci.h` and friends, as this would allow me to use this container in [SOCI](https://github.com/SOCI/soci/) instead of the ancient Oracle 11 one to test this C++ library with contemporary Oracle versions. As it is, I'd have to install [Oracle Instant Client](https://www.oracle.com/database/technologies/instant-client.html) separately, which should be possible too, but it would be more convenient to have everything inside a single container, so I wonder if you could please consider adding it?

Thanks in advance!

**Comment by gvenzl** [comment]
Hi @vadz,

Thanks a lot for using these images!

I believe the header files you are looking for are available in both the `full` and the `latest` image:

```
[gvenzl@localhost tests]$ podman run --name test --rm --entrypoint=bash -ti gvenzl/oracle-free
bash-4.4$ cd /opt/oracle/product/23ai/dbhomeFree/rdbms/public/
bash-4.4$ ls -alh
total 1.8M
drwxr-xr-x 2 oracle oinstall 4.0K Dec 13 06:39 .
drwxr-xr-x 1 oracle oinstall   19 Dec 13 07:01 ..
-rw-r--r-- 1 oracle oinstall  41K Oct  6  2023 nzerror.h
-rw-r--r-- 1 oracle oinstall  50K Oct 13  2023 nzt.h
-rw-r--r-- 1 oracle oinstall 2.1K Jul 20  2020 occi.h
-rw-r--r-- 1 oracle oinstall  12K Jul 20  2020 occiAQ.h
-rw-r--r-- 1 oracle oinstall  35K Mar 30  2022 occiCommon.h
-rw-r--r-- 1 oracle oinstall  72K Oct 12  2023 occiControl.h
-rw-r--r-- 1 oracle oinstall  40K Jul 20  2020 occiData.h
-rw-r--r-- 1 oracle oinstall  25K Jul 20  2020 occiObjects.h
-rw-r--r-- 1 oracle oinstall 248K Sep 18 10:11 oci.h
-rw-r--r-- 1 oracle oinstall 7.1K Jul 20  2020 oci1.h
-rw-r--r-- 1 oracle oinstall  11K Jul 20  2020 oci8dp.h
-rw-r--r-- 1 oracle oinstall 472K Feb 13  2024 ociap.h
-rw-r--r-- 1 oracle oinstall 6.1K Jul 20  2020 ociapr.h
-rw-r--r-- 1 oracle oinstall  42K Jul 20  2020 ocidef.h
-rw-r--r-- 1 oracle oinstall 4.0K Jul 20  2020 ocidem.h
-rw-r--r-- 1 oracle oinstall  12K Oct 16  2023 ocidfn.h
-rw-r--r-- 1 oracle oinstall 8.8K Jul 20  2020 ociextp.h
-rw-r--r-- 1 oracle oinstall  27K Dec  7  2021 ocijson.h
-rw-r--r-- 1 oracle oinstall 6.4K Jul 20  2020 ocikpr.h
-rw-r--r-- 1 oracle oinstall  509 Oct 17 18:24 ociver.h
-rw-r--r-- 1 oracle oinstall 7.8K Aug 15  2023 ocixml.h
-rw-r--r-- 1 oracle oinstall 9.4K Jun  4  2021 ocixmldb.h
-rw-r--r-- 1 oracle oinstall 110K Feb 22  2024 ocixstream.h
-rw-r--r-- 1 oracle oinstall  37K Jan 25  2022 odci.h
-rw-r--r-- 1 oracle oinstall  12K May 27  2020 orastruc.h
-rw-r--r-- 1 oracle oinstall 6.5K Jun  9  2017 oratypes.h
-rw-r--r-- 1 oracle oinstall 101K Jul 20  2020 ori.h
-rw-r--r-- 1 oracle oinstall  15K Jul 20  2020 orid.h
-rw-r--r-- 1 oracle oinstall 170K Feb 10  2022 orl.h
-rw-r--r-- 1 oracle oinstall  43K Feb 13  2024 oro.h
-rw-r--r-- 1 oracle oinstall 121K Jul 20  2020 ort.h
-rw-r--r-- 1 oracle oinstall 9.7K Jul 20  2020 xa.h
```

**Comment by vadz** [comment]
I'm awfully sorry, I indeed had taken slim images and didn't even think to check the full ones which do include these files.

I guess I could perhaps reformulate this as a request to include these headers (which are pretty small) into the slim version because it's really much slimmer (1.7GB vs 8.4GB), which means it would be much faster and consume less bandwidth to download it for the CI builds, but perhaps it doesn't matter that much due to caching, so please also feel free to just close this.

Sorry again for not checking the full image before opening this, I really should have had, and thanks again for providing these images!

**Comment by gvenzl** [comment]
Hi @vadz,

You can also use the `latest` image which is just 2.63GB. I'm trying to keep `slim` to the smallest possible size with only the core functionality. `Latest` would probably be a much safer bet to test SOCI against anyway, and as you said, it should not matter much once the image is downloaded locally.

I will close this issue for now.

Thanks again for using these images!
