### ISSUE TITLE
Using these for CI (and for development) with Ibis Framework

### ISSUE THREAD

**Issue by gforsyth** [gvenzl/oci-oracle-free#8]
Hi @gvenzl !

I just wanted to drop a note here and say thank you for putting these together!  We've used these images to set up CI and develop an Oracle backend for Ibis (https://github.com/ibis-project/ibis/pull/6126).

Not having a way to test Oracle in CI has been a blocker for us adding support to Ibis for quite some time, so we were very excited to come across this offering.  Thanks again!

**Comment by gvenzl** [comment]
Hey @gforsyth,

Wow, thanks a lot, this is really great to hear and I'm very happy that these images could help to add Oracle Database support.
If you like, I'm more than happy to [list Ibis as a user of these images in the ReadMe](https://github.com/gvenzl/oci-oracle-free/blob/main/README.md#users-of-these-images) too.

I think it can be encouraging for folks to see that others are using these images too.
So if it is OK with you, I'd gladly put Ibis as the first one on the list, just let me know.

Also, I noticed this comment [over in the PR](https://github.com/ibis-project/ibis/pull/6126#issue-1692660235):

> Data loading is hard, but is functioning. Oracle has no CREATE OR REPLACE TABLE which means we have to swallow some exceptions from calling DROP TABLE on a nonexistent table (just for testing)

It is true that Oracle doesn't have a `CREATE OR REPLACE TABLE` but it does have `DROP TABLE IF EXISTS ...`:

```sql
Connected to:
Oracle Database 23c Free, Release 23.0.0.0.0 - Developer-Release
Version 23.2.0.0.0

SQL> DROP TABLE "diamonds";
DROP TABLE "diamonds"
           *
ERROR at line 1:
ORA-00942: table or view does not exist


SQL> DROP TABLE IF EXISTS "diamonds";

Table dropped.
```

It's actually new with Oracle DB 23c, but that's exactly what you want, or at least that's exactly why we introduced it. :)

Happy to also help with other Oracle Database-related questions.

Once again, thanks a lot for your kind words and thanks for using these images! :)

**Comment by gforsyth** [comment]
> If you like, I'm more than happy to [list Ibis as a user of these images in the ReadMe](https://github.com/gvenzl/oci-oracle-free/blob/main/README.md?rgh-link-date=2023-05-26T04%3A30%3A50Z#users-of-these-images) too.

We'd be happy to be listed there!  If it's easier for me to throw up a PR, just let me know.

> It is true that Oracle doesn't have a `CREATE OR REPLACE TABLE` but it does have `DROP TABLE IF EXISTS ...`:

Oh sweet!  That's great to know.  I will happily remove our workarounds for that.

> Happy to also help with other Oracle Database-related questions.

Thank you!  And definitely let us know if you try out Ibis and find anything missing / incorrect that you think should be there.

**Comment by gvenzl** [comment]
Hey @gforsyth,

> We'd be happy to be listed there! If it's easier for me to throw up a PR, just let me know.

Amazing, thanks a lot!
I've added Ibis as the first official user of these images in the ReadMe here and over on Docker Hub!
Once again, thanks a lot, really means a lot to me!

> Thank you! And definitely let us know if you try out Ibis and find anything missing / incorrect that you think should be there.

Will do, I took a quick peek and spotted the following:

* I don't think you need this anymore, now that you have `DROP TABLE IF EXISTS` in place: https://github.com/ibis-project/ibis/blob/master/ibis/backends/oracle/tests/conftest.py#L181-L182
* Oracle DB 23c did introduce the `BOOLEAN` data type, so this should not be needed unless you want to have backward compatibility with older Oracle DB versions: https://github.com/ibis-project/ibis/blob/master/ci/schema/oracle.sql#L63-L66 (see [Boolean Data Type](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/Data-Types.html#GUID-285FFCA8-390D-4FA9-9A51-47B84EF5F83A) for more details).

**Comment by gforsyth** [comment]
Thanks @gvenzl !  Removed the gating around the `DROP TABLE`.

It's great to hear about `BOOLEAN` dtypes -- I'm going to discuss with the other Ibis maintianers how many versions of `oracle` we'd like to support, and also how to (possibly) handle offering `BOOL` when it's available.

Thanks again for all of your work on this!

**Comment by gvenzl** [comment]
You are welcome, @gforsyth!

Sounds good, and as said, feel free to ping me whenever you need something!

I'm gonna close this issue for now.
